bb

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -4,19 +4,17 @@ on: push
 
 jobs:
   echo-hello:
+    runs-on: ubuntu-latest
     steps:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Say Hello
-          run: echo "Hi,Hello"
+      - name: Say Hello
+        run: echo "Hi,Hello"
 
   echo-goodbye:
+    runs-on: ubuntu-latest 
     steps:
-      runs-on: ubuntu-latest 
-      steps:
-        - name: Failed step 
-          run: echo "failed step"
-               exit 1
+      - name: Failed step 
+        run: echo "failed step"
+             exit 1
 
-        - name: Say Good Bye 
-          run: echo "Good Bye"
+      - name: Say Good Bye 
+        run: echo "Good Bye"
